### ISSUE TITLE
'No Data' mismatch

### ISSUE THREAD

**Issue by DylanVanAssche** [oSoc19/reliability-score-backend#59]
Sometimes are application can't match the train with the Infrabel data.
If we drop the IC/S/L/... identifier, iRail and the NMBS resolve it automatically to the right one.
The train number is a unique identifier, even without the prefix.

@samvdkris Needs further testing, but if this is the key, our issue is fixed :tada:

**Comment by juliavdkris** [comment]
100% sure the train number is unique without the prefix as well? Because yeah if it is, we might as well drop it.

**Comment by DylanVanAssche** [comment]
Well I tested it on the SNCB and iRail website with success. Now we need to create a PR and test it in our application of course

**Comment by DylanVanAssche** [comment]
Hmmm I found the root cause of the missing P trains...
I was my CSV splitter script! P-trains were skipped by design 👼 

Regenerating now!

**Comment by DylanVanAssche** [comment]
Infrabel uses the old IC/L vehicle type while the NMBS uses Sxx numbers (xx are internal NMBS numbers, we don't know them directly from the data).
Dropping the vehicle type during the matching will make sure we can match them without manually mapping the IC/L types to the Sxx types.
